import { getDb, driver, dataDir } from './index';

/**
 * Apply committed migrations at startup.
 *
 * This replaces `drizzle-kit push --force`, which diffed the live database against
 * the schema and altered it in place — destructive, no history, and no way to
 * review or reverse a change. Migrations under ./drizzle are generated by
 * `npm run db:generate`, committed, and replayed in order. Drizzle records what it
 * has applied, so this is idempotent and safe to run on every boot.
 */
export async function migrate(): Promise<{ driver: string; applied: boolean; note?: string }> {
  const db = await getDb();
  const folder = './drizzle';

  if (driver === 'pglite') {
    const { migrate: run } = await import('drizzle-orm/pglite/migrator');
    await run(db as any, { migrationsFolder: folder });
    return { driver: `pglite (${dataDir})`, applied: true };
  }
  const { migrate: run } = await import('drizzle-orm/postgres-js/migrator');
  await run(db as any, { migrationsFolder: folder });
  return { driver: 'postgres', applied: true };
}
