import { getMigrationDb, driver, dataDir } from './index';

/**
 * Apply committed migrations at startup.
 *
 * This replaces `drizzle-kit push --force`, which diffed the live database against
 * the schema and altered it in place — destructive, no history, and no way to
 * review or reverse a change. Migrations under ./drizzle are generated by
 * `npm run db:generate`, committed, and replayed in order. Drizzle records what it
 * has applied, so this is idempotent and safe to run on every boot.
 */
export async function migrate(): Promise<{ driver: string; applied: boolean; note?: string }> {
  const folder = './drizzle';

  if (driver === 'pglite') {
    const { db } = await getMigrationDb();
    const { migrate: run } = await import('drizzle-orm/pglite/migrator');
    await run(db as any, { migrationsFolder: folder });
    return { driver: `pglite (${dataDir})`, applied: true };
  }
  // Managed Postgres: migrate over the DIRECT endpoint, then drop the connection.
  // Neon documents pooled connections as error-prone for ORM migrations, and a
  // lingering connection would keep a suspend-capable compute awake.
  const { db, close } = await getMigrationDb();
  try {
    const { migrate: run } = await import('drizzle-orm/postgres-js/migrator');
    await run(db as any, { migrationsFolder: folder });
  } finally {
    await close();
  }
  const direct = !!process.env.MIGRATION_DATABASE_URL;
  return { driver: 'postgres', applied: true, note: direct ? 'migrated over the direct endpoint' : 'migrated over DATABASE_URL (set MIGRATION_DATABASE_URL to the direct endpoint on a pooled provider)' };
}
